name: Deploy to OCI

on:
  workflow_run:
    workflows: ["Docker Image Release"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          passphrase: ${{ secrets.OCI_SSH_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/taylor-python:latest

            docker stop app-taylor || true
            docker rm app-taylor || true

            docker run -d \
              -p 80:5000 \
              --name app-taylor \
              ${{ secrets.DOCKER_USERNAME }}/taylor-python:latest